config/routes.rb
CrmSystem::Application.routes.draw do
  get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  scope '(:locale)' do
    resources :users
  
    root 'home#index', as: 'home'
    get 'admin' => 'admin#index'
  
    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end
  end
  

  

end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_event_calendar
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role
  belongs_to :company
  has_secure_password
  
  validates :email, presence: true, uniqueness: true
  
  def admin?
    role.title == 'admin'
  end

  def client?
    role.title == 'client'
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action { redirect_to home_url if not current_user.admin? }
  
  # GET /admin
  def index
    @total_users = User.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  
  before_action :set_i18n_locale_from_params
  before_action :authorize

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  protected
  
    def set_i18n_locale_from_params 
      if params[:locale]
        if I18n.available_locales.map(&:to_s).include? params[:locale]
          I18n.locale = params[:locale]
        else
          flash.now[:notice] = "#{params[:locale]} #{t('translation_not_available')}"
          logger.error flash.now[:notice]
        end 
      end
    end
    
    def default_url_options
      { locale: I18n.locale }
    end
  
    def authorize
      if current_user.nil?
        redirect_to login_url, notice: "Please log in"
      end
    end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  
  def index
    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i

    @shown_month = Date.civil(@year, @month)

    @event_strips = Event.event_strips_for_month(@shown_month)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authorize
  
  # GET /
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize, only: [:new, :create]
  
  # GET /login
  def new
  end

  # POST /login
  def create
    user = User.find_by(email: params[:email])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
    else
      redirect_to login_url, alert: "Invalid user/password combination"
    end
  end

  # DELETE /logout
  def destroy
    session[:user_id] = nil
    redirect_to home_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize, only: [:new, :create]
  before_action :admin_pemissions, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.role = Role.find_by_title 'client'

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User #{@user.email} was successfully created." }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: "User #{@user.email} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
    
    def admin_pemissions
      redirect_to home_url if not current_user.admin?
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end
  
  # custom options for this calendar
  def event_calendar_opts
    { 
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>"    }
  end

  def event_calendar
    # args is an argument hash containing :event, :day, and :options
    calendar event_calendar_opts do |args|
      event = args[:event]
      %(<a href="/events/#{event.id}" title="#{h(event.name)}">#{h(event.name)}</a>)
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1> It's <%= Time.now %>
We have <%= pluralize(@total_users, "user") %>.

app/views/calendar/index.html.erb
<!-- Probably move the stylesheet to you layout. Also make sure you include the javascript. -->
<%= stylesheet_link_tag "event_calendar" %>

<h1>Calendar</h1>

<%= raw(event_calendar) %>

app/views/home/index.html.erb
<%= t '.home_title_html' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CRM system</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body id="<%= controller.controller_name %>">
  <div id="banner">
    <% image_tag("logo.png") %>
    <%= @page_title || t('.title') %>
    <div id="login">
      <% if session[:user_id] %>
        <%= "Hello #{User.find(session[:user_id]).email}" %>
        <%= link_to t('logout'), logout_url, method: :delete %>
      <% else %>
        <%= link_to t('login'), login_path %>
      <% end %>
    </div>
  </div>
  <div id="columns">
    <div id="side"> 
      <ul>
        <% if current_user %>
          <% if current_user.admin? %>
            <li><%= link_to_unless_current t('.home_page'), home_path %></li>
            <li><%= link_to_unless_current t('.admin_page'), admin_path %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
    <div id="main"> 
      <% if notice %>
        <p id="notice"><%= notice %></p>
      <% end %>
    
      <%= yield %>
    
    </div>
    <div id="footer">
      <%= t '.сopyright' %>
    </div>
  </div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<% if notice %>
  <p id="notice"><%= notice %></p> 
<% end %>
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>